### PR TITLE
Proposing some fly-by quality updates to contribution page

### PR DESCRIPTION
**Pull request by benjaoming**
There were a number of small typos and similar that I've updated here.

I think we need to sort out what we need Jira for WRT public interaction.

1. It's mixed up with links to GitHub, which is confusing
2. Jira isn't publicly available

I'll go ahead and open an issue for that later.

### CODE REVIEW

**Comment by benjaoming** [comment]
Another note: I can't see the GitBook preview without signing up to GitBook.

**Comment by rachellawson** [comment]
Thanks for checking! 

Agreed that there are some improvements we can make to the contribution page - now that we are getting closer to having the finalised structure, we can work on these but this is a great start!

You are correct that access to gitbook is required to see the preview and I’m happy to invite you!

The CLA is still in dev so it is not a required item to merge right now.

**Comment by rachellawson** [comment]
Oh, and it might well be easier in the end to simply add the GitHub issue number rather than Jira. That way, we don’t need to wire up Jira issues to commits

**Comment by rachellawson** [comment]
Just noting here that it will probably make sense to squash changes we make here and then cherry-pick this PR commit back onto the 0.9.0 branch so that the contribution.md on the published version reflects the same as the development one.

**Comment by benjaoming** [comment]
Thanks for the feedback @rachellawson :)

> Just noting here that it will probably make sense to squash changes we make here and then cherry-pick this PR commit back onto the 0.9.0 branch so that the contribution.md on the published version reflects the same as the development one.

If you want the PR re-targeted (it might work), you can use the edit function.

image

image

**Comment by rachellawson** [comment]
Also, we should start by pointing out multiple versions of the spec are published and they should make sure they are looking at the development version when suggesting changes -- their idea might already have been thought of!

**Pull request merged**
